window.GGH_SEED = {
  "news": [
    {
      "id": "N-1",
      "title": "Korea’s 2026 visa reforms: more part-time hours and easier job-seeking for graduates",
      "desc": "On 4 May 2026 the Korean government approved a package of visa reforms aimed at attracting and keeping international talent. Several of the changes directly aff",
      "category": "Visa Update",
      "status": "published",
      "updated": "May 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "korea-2026-visa-reforms-students",
      "body": "On 4 May 2026 the Korean government approved a package of visa reforms aimed at attracting and keeping international talent. Several of the changes directly affect students on D-2 and D-4 visas and are good news for Myanmar students planning to study in Korea.\n\nPart-time work: allowed weekly hours during the semester have been expanded, with some degree students now permitted up to 35 hours per week depending on their university’s certification status and their TOPIK level. As a guide, undergraduates with TOPIK 3 or higher can typically work around 25 hours a week, rising to 30 with TOPIK 4, while graduate students with TOPIK 4 or higher can reach the upper limit. Students with TOPIK 4 or above may also work unlimited hours during the summer and winter vacations. Language-course students on a D-4 visa still need to complete six months of study before applying for a work permit.\n\nAfter graduation: the D-10 job-seeker visa has been widened, and graduates in STEM fields now have a simpler route to the F-2 long-term residency visa. A new K-CORE (Korea College-to-Regional Employment) scheme helps foreign graduates of technical colleges move into stable jobs with manufacturers outside the Seoul area.\n\nWhat it means for you: choosing a certified university, and reaching TOPIK 3–4 before or during your first year, now has a real impact on how much you can earn while studying and on your options after graduation. Our advisors can explain which of our partner institutions are certified and how the rules apply to your program.\n\nSources: Korean Ministry of Justice announcements as reported by VisaVerge and Korean immigration guides, May–June 2026. Rules can change; always confirm current conditions with the immigration office or your university’s international office.",
      "image": "https://images.unsplash.com/photo-1546874177-9e664107314e?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-2",
      "title": "TOPIK 2026: full test calendar and how to register from Myanmar",
      "desc": "TOPIK (Test of Proficiency in Korean) is the qualification most Korean universities and language institutes use to assess your Korean level, and a higher level ",
      "category": "Topik",
      "status": "published",
      "updated": "Updated September 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "topik-2026-test-dates",
      "body": "TOPIK (Test of Proficiency in Korean) is the qualification most Korean universities and language institutes use to assess your Korean level, and a higher level also unlocks more part-time work hours once you are in Korea. Here is the 2026 schedule announced by the National Institute for International Education (NIIED).\n\nPaper-based test (PBT): 104th – 11 January (Korea only); 105th – 11–12 April; 106th – 17 May; 107th – 4–5 July; 108th – 17–18 October; 109th – 15 November. Overseas registration windows close roughly two months before each test — for example 4–10 August for the October sitting and 1–7 September for the November sitting.\n\nInternet-based test (IBT): 11th – 28 February (Korea only); 12th – 21 March; 13th – 13 June; 14th – 12 September; 15th – 24 October; 16th – 28 November. IBT sittings are being offered in more countries each year.\n\nRegistering from Myanmar: overseas registration is handled through the local host institution rather than the Korean website, and dates and seat numbers vary by country. Check the Korean Embassy in Yangon and the Korean Cultural Centre announcements as soon as a registration window opens, because seats fill quickly. The 2027 calendar is usually published in November or December.\n\nNeed a study plan? Our Korean language program advisors can help you set a target level and prepare in time for your university intake.\n\nSources: NIIED / TOPIK official schedule; Korea JoongAng Daily, November 2025.",
      "image": "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-3",
      "title": "D-4-1 Korean language visa: what Myanmar students need to prepare",
      "desc": "The D-4-1 visa is the standard route for students who want to learn Korean at a university language institute before moving on to a degree. The process is strai",
      "category": "Study Guide",
      "status": "published",
      "updated": "August 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "d-4-1-visa-checklist-myanmar",
      "body": "The D-4-1 visa is the standard route for students who want to learn Korean at a university language institute before moving on to a degree. The process is straightforward when you plan ahead — most students should allow two to three months from application to departure.\n\nStep 1 – Admission: apply to a university-affiliated Korean language institute and receive your Certificate of Admission (CoA). Institutes usually run four intakes a year (March, June, September and December) and each level takes about ten weeks.\n\nStep 2 – Documents: a valid passport, the CoA, your high-school graduation certificate and transcripts, a study plan, passport photos, and proof of finances. Institutes and the embassy generally expect a bank balance of around USD 7,000–10,000 in the student’s or a parent’s name, held for a specified period. Some institutes also ask for a family relationship certificate or a sponsor letter.\n\nStep 3 – Visa application: complete the application online at visa.mofa.go.kr, then submit the printed form and documents in person at the VFS Global Visa Application Centre in Yangon, where your fingerprints and photo are taken. Embassy processing normally takes two to four weeks, so apply as soon as your CoA arrives.\n\nAfter arrival: register for your Residence Card within 90 days, and remember that part-time work is only permitted after six months of study and with a permit from immigration.\n\nEvery institute has slightly different requirements and fees. Book a consultation and we will prepare a document checklist for the institute you choose.",
      "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-4",
      "title": "Global Korea Scholarship: what the 2026 round tells us about applying for 2027",
      "desc": "The Global Korea Scholarship (GKS) is the Korean government’s fully funded scholarship for international students, and Myanmar is an eligible country. For 2026 ",
      "category": "Scholarships",
      "status": "published",
      "updated": "July 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "gks-scholarship-2026-2027",
      "body": "The Global Korea Scholarship (GKS) is the Korean government’s fully funded scholarship for international students, and Myanmar is an eligible country. For 2026 the programme invited 2,000 graduate students and 280 undergraduate and associate-degree students — 150 through the Embassy Track and 130 through the University Track.\n\nWhat it covers: full tuition, a one-year Korean language course before your degree, a monthly living allowance, round-trip airfare, a settlement grant on arrival, health insurance, and a bonus for students who achieve a high TOPIK level.\n\nHow it works: applicants choose either the Embassy Track (applying through the Korean Embassy in Yangon) or the University Track (applying directly to one designated university). The 2026 graduate round accepted applications from 12 to 25 February through the Study in Korea website, and the undergraduate round is normally announced in the autumn of the year before entry.\n\nGetting ready for 2027: strong academic results, a clear study plan, good recommendation letters and a TOPIK or English proficiency score all strengthen an application. Because the Embassy Track is limited to a small number of places per country, starting early matters. Our advisors can review your profile and help you decide which track and universities to target.\n\nSources: Embassy of the Republic of Korea in Myanmar; Study in Korea (studyinkorea.go.kr) GKS notices, 2026.",
      "image": "https://images.unsplash.com/photo-1627556704302-624286467c65?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-5",
      "title": "Korea passes 250,000 international students on the road to “Study Korea 300K”",
      "desc": "Korea hosted 253,434 international students in 2025, the highest number on record and well on the way to the government’s target of 300,000 students by 2027 und",
      "category": "News",
      "status": "published",
      "updated": "June 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "study-korea-300k-milestone",
      "body": "Korea hosted 253,434 international students in 2025, the highest number on record and well on the way to the government’s target of 300,000 students by 2027 under the Study Korea 300K plan.\n\nThe plan is behind many of the changes students are seeing on the ground: more English-taught degree programmes, a growing list of universities certified by the Ministry of Education (which enjoy simpler visa screening for their students), expanded regional scholarships, and stronger links between colleges and employers outside Seoul.\n\nFor students from Southeast Asia, the practical effect is more choice. Regional universities and technical colleges are actively recruiting, often with lower tuition and living costs than the capital, and pathway programs that combine language study with a degree are becoming more common.\n\nGo Go Hankuk works with universities, colleges and language institutes across Korea. If you are weighing Seoul against a regional city, or a language course against a direct degree entry, talk to us about the options that match your budget and goals.\n\nSource: Korean Ministry of Education statistics reported in 2026 study-in-Korea guides.",
      "image": "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-6",
      "title": "Thailand as a stepping stone to Korea: Korean is now Thailand’s No. 2 foreign language",
      "desc": "Interest in Korea is growing fast in Thailand. Korean has become the second most popular foreign language on the Thai university entrance test, and Thai univers",
      "category": "Pathways",
      "status": "published",
      "updated": "April 2026",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "thailand-korea-pathway-2026",
      "body": "Interest in Korea is growing fast in Thailand. Korean has become the second most popular foreign language on the Thai university entrance test, and Thai universities are expanding Korean-language and Korea-focused programmes in response.\n\nIn April 2026 Chulalongkorn University in Bangkok held a Career Pathway Promotion Program with Korean companies, bringing together government agencies and Korean businesses to offer internships, recruitment and career preparation to Korean-language students — a sign of how closely education and employment links between the two countries are developing.\n\nWhy this matters for Myanmar students: Thailand is nearby, affordable and has a well-developed international education sector. Our Thailand to Korea Program lets students begin with a preparatory or language course at a partner institution in Thailand, then progress to a language institute, college or university in Korea once academic and language conditions are met — building confidence and skills before the bigger move.\n\nAsk our advisors for the current partner institutions, progression conditions and the visa steps for each stage of the pathway.\n\nSources: Korea.net; Chulalongkorn University news, April 2026.",
      "image": "https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-7",
      "title": "Your study-abroad journey starts with five questions",
      "desc": "Start with what you want to study and why. Then think about where you would feel comfortable living, what you can budget for tuition and daily life, when you ho",
      "category": "Study Guide",
      "status": "published",
      "updated": "4 min read",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "study-abroad-five-questions",
      "body": "Start with what you want to study and why. Then think about where you would feel comfortable living, what you can budget for tuition and daily life, when you hope to begin, and which entry requirements you need to meet. Bring these five answers to an advisor so your first conversation has a clear starting point.",
      "image": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-8",
      "title": "A calmer way to prepare your university application",
      "desc": "Make one checklist for each university. Record official deadlines and document requirements, allow time for references and translations, and keep copies of ever",
      "category": "Application Tips",
      "status": "published",
      "updated": "3 min read",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "prepare-your-application",
      "body": "Make one checklist for each university. Record official deadlines and document requirements, allow time for references and translations, and keep copies of everything you submit. Review the university’s own instructions before applying; requirements can differ between courses and intakes.",
      "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"
    },
    {
      "id": "N-9",
      "title": "Let’s talk about your next chapter",
      "desc": "This is the space for agency open days, information sessions, and workshops. Confirmed dates and registration details will be published here when available. In ",
      "category": "Events & Conversations",
      "status": "published",
      "updated": "Upcoming sessions",
      "author": "Go Go Hankuk",
      "publishDate": "Publish immediately",
      "slug": "next-chapter-sessions",
      "body": "This is the space for agency open days, information sessions, and workshops. Confirmed dates and registration details will be published here when available. In the meantime, prepare your questions about courses, destinations, budgets, and application timelines.",
      "image": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800&q=80"
    }
  ],
  "universities": [
    {
      "id": "U-1",
      "slug": "ajou-university",
      "name": "Ajou University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/ajou-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 1
    },
    {
      "id": "U-2",
      "slug": "baekseok-university",
      "name": "Baekseok University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/baekseok-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 2
    },
    {
      "id": "U-3",
      "slug": "busan-university-of-foreign-studies",
      "name": "Busan University of foreign studies",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/busan-university-of-foreign-studies.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 3
    },
    {
      "id": "U-4",
      "slug": "chosun-university",
      "name": "Chosun University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/chosun-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 4
    },
    {
      "id": "U-5",
      "slug": "chung-cheong-university",
      "name": "Chung Cheong University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/chung-cheong-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 5
    },
    {
      "id": "U-6",
      "slug": "chungbuk-health-science-university",
      "name": "Chungbuk Health & Science University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/chungbuk-health-science-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 6
    },
    {
      "id": "U-7",
      "slug": "chungnam-national-university",
      "name": "Chungnam National University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/chungnam-national-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 7
    },
    {
      "id": "U-8",
      "slug": "donggang-university",
      "name": "Donggang University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/donggang-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 8
    },
    {
      "id": "U-9",
      "slug": "dongguk-university",
      "name": "Dongguk University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/dongguk-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 9
    },
    {
      "id": "U-10",
      "slug": "duksung-university",
      "name": "Duksung University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/duksung-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 10
    },
    {
      "id": "U-11",
      "slug": "hansung-university",
      "name": "Hansung University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/hansung-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 11
    },
    {
      "id": "U-12",
      "slug": "hanyang-university",
      "name": "Hanyang University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/hanyang-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 12
    },
    {
      "id": "U-13",
      "slug": "inha-university",
      "name": "Inha University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/inha-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 13
    },
    {
      "id": "U-14",
      "slug": "international-graduate-school-of-english",
      "name": "International graduate school of english",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/international-graduate-school-of-english.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 14
    },
    {
      "id": "U-15",
      "slug": "jeonju-university",
      "name": "Jeonju University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/jeonju-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 15
    },
    {
      "id": "U-16",
      "slug": "keimyung-university",
      "name": "Keimyung University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/keimyung-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 16
    },
    {
      "id": "U-17",
      "slug": "korea-university",
      "name": "Korea University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/korea-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 17
    },
    {
      "id": "U-18",
      "slug": "kyung-hee-university",
      "name": "Kyung Hee University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/kyung-hee-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 18
    },
    {
      "id": "U-19",
      "slug": "kyungsung-university",
      "name": "Kyungsung University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/kyungsung-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 19
    },
    {
      "id": "U-20",
      "slug": "mokwon-university",
      "name": "Mokwon University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/mokwon-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 20
    },
    {
      "id": "U-21",
      "slug": "pusan-university",
      "name": "Pusan University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/pusan-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 21
    },
    {
      "id": "U-22",
      "slug": "pyeongtaek-university",
      "name": "Pyeongtaek University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/pyeongtaek-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 22
    },
    {
      "id": "U-23",
      "slug": "seojeong-university",
      "name": "Seojeong University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/seojeong-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 23
    },
    {
      "id": "U-24",
      "slug": "seoul-theology-university",
      "name": "Seoul Theology University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/seoul-theology-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 24
    },
    {
      "id": "U-25",
      "slug": "seoul-womens-university",
      "name": "Seoul Women’s University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/seoul-womens-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 25
    },
    {
      "id": "U-26",
      "slug": "sookmyung-university",
      "name": "Sookmyung University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/sookmyung-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 26
    },
    {
      "id": "U-27",
      "slug": "sungkyul-university",
      "name": "Sungkyul University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/sungkyul-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 27
    },
    {
      "id": "U-28",
      "slug": "sungkyunkwan-university",
      "name": "Sungkyunkwan University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/sungkyunkwan-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 28
    },
    {
      "id": "U-29",
      "slug": "sungshin-university",
      "name": "Sungshin University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/sungshin-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 29
    },
    {
      "id": "U-30",
      "slug": "sunmoon-university",
      "name": "Sunmoon University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/sunmoon-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 30
    },
    {
      "id": "U-31",
      "slug": "the-catholic-university",
      "name": "The Catholic University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/the-catholic-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 31
    },
    {
      "id": "U-32",
      "slug": "university-of-ulsan",
      "name": "University of Ulsan",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/university-of-ulsan.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 32
    },
    {
      "id": "U-33",
      "slug": "wonkwang-university",
      "name": "Wonkwang University",
      "logo": "https://gogohankuktest.netlify.app/assets/universities/wonkwang-university.png",
      "location": "",
      "programs": "",
      "website": "",
      "status": "published",
      "order": 33
    }
  ],
  "team": [
    {
      "id": "T-3",
      "name": "Ei Ei Khaing",
      "role": "Manager / Operation",
      "group": "Our Team",
      "status": "published",
      "initials": "EE",
      "order": 3,
      "intro": "Manager / Operation",
      "bio": "Ei Ei Khaing — Manager / Operation."
    },
    {
      "id": "T-4",
      "name": "Chit Ko",
      "role": "Manager / HR",
      "group": "Our Team",
      "status": "published",
      "initials": "CK",
      "order": 4,
      "intro": "Manager / HR",
      "bio": "Chit Ko — Manager / HR."
    },
    {
      "id": "T-5",
      "name": "Hsu Pyae Pyae Maung",
      "role": "Instructor / Language Training",
      "group": "Our Team",
      "status": "published",
      "initials": "HP",
      "order": 5,
      "intro": "Instructor / Language Training",
      "bio": "Hsu Pyae Pyae Maung — Instructor / Language Training."
    },
    {
      "id": "T-6",
      "name": "Yin Oo May",
      "role": "Position / department",
      "group": "Our Team",
      "status": "published",
      "initials": "YO",
      "order": 6,
      "intro": "Position / department",
      "bio": "Yin Oo May — Position / department."
    },
    {
      "id": "T-7",
      "name": "Staff name",
      "role": "Position / department",
      "group": "Our Team",
      "status": "draft",
      "initials": "SN",
      "order": 7,
      "intro": "Position / department",
      "bio": "Staff name — Position / department."
    },
    {
      "id": "T-8",
      "name": "Staff name",
      "role": "Position / department",
      "group": "Our Team",
      "status": "draft",
      "initials": "SN",
      "order": 8,
      "intro": "Position / department",
      "bio": "Staff name — Position / department."
    }
  ],
  "hero": {
    "title": "Study in Korea",
    "description": "Your future begins with<br>Go Go Hankuk Education",
    "image": "assets/figma/hero-bg.jpg"
  }
};
